lf-file:
  domain: http://127.0.0.1
  local-file-path: /usr/local/files
  local-file-prefix: /p

server:
  port: 8082
  servlet:
    context-path: /manager
spring:
  application:
    name: lf-file-fmanager