lf-file:
  domain: http://127.0.0.1:8082
#  local-file-path: /usr/local/files
  local-file-path: D:\temp\file\
  local-file-prefix: /p

server:
  port: 8082
  servlet:
    context-path: /manager
spring:
  application:
    name: lf-file-fmanager
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifepoem_warehouse
mybatis:
  mapper-locations: classpath:mapper/*.xml

