server:
  port: 8081
  servlet:
    context-path: /store
spring:
  application:
    name: lf-file-store

lf-file:
  domain: http://127.0.0.1:8082
  #  local-file-path: /usr/local/files
  local-file-path: D:\temp\file\
  local-file-prefix: /p